//! Transpiled from COBOL program: PRG1
//! Generated by Easy COBOL Migrator on 2026-03-23T06:12:37

#![allow(dead_code, non_upper_case_globals, static_mut_refs, unused_unsafe)]

use std::process;


// Working Storage variables (static mut for COBOL global state model)
#[allow(unused_variables)] static mut return_code: i64 = 0;

fn main() {
    unsafe {

        println!("{}", "HELLO WORLD!".to_string());
        process::exit(0);
    }
}

