//! Transpiled from COBOL program: EDITED-NUM-TEST
//! Generated by Easy COBOL Migrator on 2026-03-23T05:38:21

#![allow(dead_code, non_upper_case_globals, static_mut_refs, unused_unsafe)]

use std::process;

fn cobol_edit_fmt(value: f64, pic: &str) -> String {
    let mut exp = String::new();
    let chars: Vec<char> = pic.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let ch = chars[i].to_ascii_uppercase();
        if i + 1 < chars.len() && chars[i + 1] == '(' {
            if let Some(cl) = pic[i+2..].find(')') {
                let n: usize = pic[i+2..i+2+cl].parse().unwrap_or(1);
                for _ in 0..n { exp.push(ch); }
                i = i + 2 + cl + 1; continue;
            }
        }
        exp.push(ch); i += 1;
    }
    let exp_chars: Vec<char> = exp.chars().collect();
    let mut float_sym: Option<char> = None; let mut float_cnt = 0i32;
    for &c in &exp_chars {
        if c == '$' || c == '+' || c == '-' {
            if float_sym.is_none() || float_sym == Some(c) { float_sym = Some(c); float_cnt += 1; }
        }
    }
    if float_cnt < 2 { float_sym = None; }
    let mut slots: Vec<(char, bool)> = Vec::new();
    let mut n_dig = 0i32; let mut dec_at = -1i32;
    for &c in &exp_chars {
        if c == '9' || c == 'Z' || c == '*' { slots.push((c, true)); n_dig += 1; }
        else if (c == '$' || c == '+' || c == '-') && float_sym == Some(c) { slots.push((c, true)); n_dig += 1; }
        else if c == 'V' { dec_at = n_dig; }
        else if c == '.' { dec_at = n_dig; slots.push(('.', false)); }
        else if c == ',' || c == '/' || c == 'B' || c == '0' { slots.push((c, false)); }
        else if (c == '$' || c == '+' || c == '-') && float_sym != Some(c) { slots.push((c, false)); }
    }
    if dec_at < 0 { dec_at = n_dig; }
    let dec_dig = n_dig - dec_at;
    let neg = value < 0.0; let av = value.abs();
    let sc = (av * 10f64.powi(dec_dig)).round() as i64;
    let mut digs = format!("{}", sc);
    while (digs.len() as i32) < n_dig { digs = format!("0{}", digs); }
    if (digs.len() as i32) > n_dig { digs = digs[digs.len() - n_dig as usize..].to_string(); }
    let digs_bytes = digs.as_bytes();
    let mut f_sig = n_dig;
    for i in 0..n_dig as usize { if digs_bytes[i] != b'0' { f_sig = i as i32; break; } }
    let mut f_pos = -1i32;
    if let Some(fs) = float_sym {
        let mut last_f = -1i32; let mut di = 0i32;
        for &(t, isd) in &slots { if isd { if t == fs { last_f = di; } di += 1; } }
        f_pos = if f_sig > 0 && last_f >= 0 { std::cmp::min(f_sig - 1, last_f) } else if f_sig == n_dig { last_f } else { -1 };
    }
    let mut res = String::new(); let mut di = 0i32; let mut seen = false;
    for &(t, isd) in &slots {
        if isd {
            let d = digs_bytes[di as usize] as char; let lz = !seen && d == '0';
            if t == '9' { res.push(d); seen = true; }
            else if t == 'Z' { res.push(if lz { ' ' } else { d }); if !lz { seen = true; } }
            else if t == '*' { res.push(if lz { '*' } else { d }); if !lz { seen = true; } }
            else {
                if di == f_pos { res.push(if t == '$' { '$' } else if neg { '-' } else if t == '+' { '+' } else { ' ' }); seen = true; }
                else if lz { res.push(' '); }
                else { res.push(d); seen = true; }
            }
            di += 1;
        } else {
            if t == '.' { res.push('.'); }
            else if t == ',' { res.push(if seen { ',' } else { ' ' }); }
            else if t == '/' { res.push('/'); }
            else if t == 'B' { res.push(' '); }
            else if t == '0' { res.push('0'); }
            else if t == '$' { res.push('$'); }
            else if t == '+' || t == '-' { res.push(if neg { '-' } else if t == '+' { '+' } else { ' ' }); }
        }
    }
    res
}


// Working Storage variables (static mut for COBOL global state model)
static mut ws_amount: f64 = 0.0;
static mut ws_small: f64 = 0.0;
static mut ws_zero: f64 = 0.0;
static mut ws_negative: f64 = 0.0;
static mut ws_edit1: String = String::new();
static mut ws_edit2: String = String::new();
static mut ws_edit3: String = String::new();
static mut ws_edit4: String = String::new();
static mut ws_bwz: String = String::new();
#[allow(unused_variables)] static mut return_code: i64 = 0;

fn main() {
    unsafe { ws_amount = 12345.67_f64; }
    unsafe { ws_small = 42.50_f64; }
    unsafe { ws_zero = 0 as f64; }
    unsafe { ws_negative = -1234.56_f64; }
    unsafe { ws_edit1 = cobol_edit_fmt(0.0, "-ZZ,ZZ9.99"); }
    unsafe { ws_edit2 = cobol_edit_fmt(0.0, "$$$,$$9.99"); }
    unsafe { ws_edit3 = cobol_edit_fmt(0.0, "*(5)9.99"); }
    unsafe { ws_edit4 = cobol_edit_fmt(0.0, "ZZ,ZZ9.99"); }
    unsafe { ws_bwz = cobol_edit_fmt(0.0, "ZZ,ZZ9.99"); }
    unsafe {

        println!("{}", "=== EDITED NUMERIC TESTS ===".to_string());
        ws_edit1 = cobol_edit_fmt(ws_amount as f64, "-ZZ,ZZ9.99");
        println!("{}{}{}", "Edit1 (large):  [".to_string(), ws_edit1, "]".to_string());
        ws_edit1 = cobol_edit_fmt(ws_small as f64, "-ZZ,ZZ9.99");
        println!("{}{}{}", "Edit1 (small):  [".to_string(), ws_edit1, "]".to_string());
        ws_edit1 = cobol_edit_fmt(ws_negative as f64, "-ZZ,ZZ9.99");
        println!("{}{}{}", "Edit1 (neg):    [".to_string(), ws_edit1, "]".to_string());
        ws_edit2 = cobol_edit_fmt(ws_amount as f64, "$$$,$$9.99");
        println!("{}{}{}", "Edit2 (large):  [".to_string(), ws_edit2, "]".to_string());
        ws_edit2 = cobol_edit_fmt(ws_small as f64, "$$$,$$9.99");
        println!("{}{}{}", "Edit2 (small):  [".to_string(), ws_edit2, "]".to_string());
        ws_edit3 = cobol_edit_fmt(ws_amount as f64, "*(5)9.99");
        println!("{}{}{}", "Edit3 (large):  [".to_string(), ws_edit3, "]".to_string());
        ws_edit3 = cobol_edit_fmt(ws_small as f64, "*(5)9.99");
        println!("{}{}{}", "Edit3 (small):  [".to_string(), ws_edit3, "]".to_string());
        ws_edit4 = cobol_edit_fmt(ws_amount as f64, "ZZ,ZZ9.99");
        println!("{}{}{}", "Edit4 (large):  [".to_string(), ws_edit4, "]".to_string());
        ws_edit4 = cobol_edit_fmt(ws_small as f64, "ZZ,ZZ9.99");
        println!("{}{}{}", "Edit4 (small):  [".to_string(), ws_edit4, "]".to_string());
        ws_bwz = if ws_zero as f64 == 0.0 { " ".repeat(8).to_string() } else { cobol_edit_fmt(ws_zero as f64, "ZZ,ZZ9.99") };
        println!("{}{}{}", "BWZ (zero):     [".to_string(), ws_bwz, "]".to_string());
        ws_bwz = if ws_small as f64 == 0.0 { " ".repeat(8).to_string() } else { cobol_edit_fmt(ws_small as f64, "ZZ,ZZ9.99") };
        println!("{}{}{}", "BWZ (nonzero):  [".to_string(), ws_bwz, "]".to_string());
        process::exit(0);
    }
}

