//! Transpiled from COBOL program: SIZE-ERROR-TEST
//! Generated by Easy COBOL Migrator on 2026-03-23T05:38:13

#![allow(dead_code, non_upper_case_globals, static_mut_refs, unused_unsafe)]

use std::process;


// Working Storage variables (static mut for COBOL global state model)
static mut ws_small: i64 = 0;
static mut ws_large: i64 = 0;
static mut ws_signed: i64 = 0;
static mut ws_val_a: i64 = 0;
static mut ws_val_b: i64 = 0;
static mut ws_overflow: i64 = 0;
#[allow(unused_variables)] static mut return_code: i64 = 0;

fn main() {
    unsafe { ws_small = 0; }
    unsafe { ws_large = 0; }
    unsafe { ws_signed = 0; }
    unsafe { ws_val_a = 995; }
    unsafe { ws_val_b = 6; }
    unsafe { ws_overflow = 0; }
    unsafe {

        println!("{}", "=== ON SIZE ERROR TESTS ===".to_string());
        ws_overflow = 0;
        {  // ON SIZE ERROR guard
            let mut _size_error = false;
            if !_size_error {
                let _temp_result: f64 = ((ws_val_a as f64) + (ws_val_b as f64)) as f64;
                if _temp_result > 999.0000000000_f64 || _temp_result < 0.0000000000_f64 {
                    _size_error = true;
                } else {
                    ws_small = ((ws_val_a as f64) + (ws_val_b as f64)) as i64;
                }
            }
            if _size_error {
                ws_overflow = 1;
            }
        }
        println!("{}{:03}{}{:01}", "Case A: WS-SMALL=".to_string(), ws_small, " overflow=".to_string(), ws_overflow);
        ws_overflow = 0;
        {  // ON SIZE ERROR guard
            let mut _size_error = false;
            if !_size_error {
                let _temp_result: f64 = ((ws_val_a as f64) + (ws_val_b as f64)) as f64;
                if _temp_result > 9999999.0000000000_f64 || _temp_result < 0.0000000000_f64 {
                    _size_error = true;
                } else {
                    ws_large = ((ws_val_a as f64) + (ws_val_b as f64)) as i64;
                }
            }
            if _size_error {
                ws_overflow = 1;
            }
        }
        println!("{}{:07}{}{:01}", "Case B: WS-LARGE=".to_string(), ws_large, " overflow=".to_string(), ws_overflow);
        ws_overflow = 0;
        {  // ON SIZE ERROR guard
            let mut _size_error = false;
            if !_size_error {
                let _temp_result: f64 = ((ws_val_a as f64) * (ws_val_b as f64)) as f64;
                if _temp_result > 999.0000000000_f64 || _temp_result < 0.0000000000_f64 {
                    _size_error = true;
                } else {
                    ws_small = ((ws_val_a as f64) * (ws_val_b as f64)) as i64;
                }
            }
            if _size_error {
                ws_overflow = 1;
            }
        }
        println!("{}{:03}{}{:01}", "Case C: WS-SMALL=".to_string(), ws_small, " overflow=".to_string(), ws_overflow);
        ws_overflow = 0;
        ws_overflow = 1;
        println!("{}{:03}{}{:01}", "Case D: WS-SMALL=".to_string(), ws_small, " overflow=".to_string(), ws_overflow);
        ws_overflow = 0;
        {  // ON SIZE ERROR guard
            let mut _size_error = false;
            if !_size_error {
                let _temp_result: f64 = ((ws_val_a as f64) / (0 as f64)) as f64;
                if _temp_result > 999.0000000000_f64 || _temp_result < 0.0000000000_f64 {
                    _size_error = true;
                } else {
                    ws_small = ((ws_val_a as f64) / (0 as f64)) as i64;
                }
            }
            if _size_error {
                ws_overflow = 1;
            }
        }
        println!("{}{:03}{}{:01}", "Case E: WS-SMALL=".to_string(), ws_small, " overflow=".to_string(), ws_overflow);
        ws_overflow = 0;
        {  // ON SIZE ERROR guard
            let mut _size_error = false;
            if !_size_error {
                let _temp_result: f64 = ((ws_val_a as f64 + ws_val_b as f64)) as f64;
                if _temp_result > 999.0000000000_f64 || _temp_result < 0.0000000000_f64 {
                    _size_error = true;
                } else {
                    ws_small = ((ws_val_a as f64 + ws_val_b as f64)) as i64;
                }
            }
            if _size_error {
                ws_overflow = 1;
            }
        }
        println!("{}{:03}{}{:01}", "Case F: WS-SMALL=".to_string(), ws_small, " overflow=".to_string(), ws_overflow);
        ws_overflow = 0;
        {  // ON SIZE ERROR guard
            let mut _size_error = false;
            if !_size_error {
                let _temp_result: f64 = ((5 as f64 - 10 as f64)) as f64;
                if _temp_result > 999.0000000000_f64 || _temp_result < 0.0000000000_f64 {
                    _size_error = true;
                } else {
                    ws_small = ((5 as f64 - 10 as f64)) as i64;
                }
            }
            if _size_error {
                ws_overflow = 1;
            }
        }
        println!("{}{:03}{}{:01}", "Case G: WS-SMALL=".to_string(), ws_small, " overflow=".to_string(), ws_overflow);
        ws_overflow = 0;
        {  // ON SIZE ERROR guard
            let mut _size_error = false;
            if !_size_error {
                let _temp_result: f64 = ((5 as f64 - 10 as f64)) as f64;
                if _temp_result > 999.0000000000_f64 || _temp_result < -999.0000000000_f64 {
                    _size_error = true;
                } else {
                    ws_signed = ((5 as f64 - 10 as f64)) as i64;
                }
            }
            if _size_error {
                ws_overflow = 1;
            }
        }
        println!("{}{:+04}{}{:01}", "Case H: WS-SIGNED=".to_string(), ws_signed, " overflow=".to_string(), ws_overflow);
        process::exit(0);
    }
}

