//! Transpiled from COBOL program: COPY-STRUCT
//! Generated by Easy COBOL Migrator on 2026-03-23T05:38:30

#![allow(dead_code, non_upper_case_globals, static_mut_refs, unused_unsafe)]

use std::process;


#[derive(Debug, Clone, Default)]
struct SavingsAccount {
    savings_acct_id: String,
    savings_acct_name: String,
    savings_balance: f64,
    savings_int_rate: f64,
    savings_status: String,
}


#[derive(Debug, Clone, Default)]
struct CheckingAccount {
    checking_acct_id: String,
    checking_acct_name: String,
    checking_balance: f64,
    checking_int_rate: f64,
    checking_status: String,
}


#[derive(Debug, Clone, Default)]
struct CreditAccount {
    credit_acct_id: String,
    credit_acct_name: String,
    credit_balance: f64,
    credit_int_rate: f64,
    credit_status: String,
}


fn savings_active(p_savings_status: &str) -> bool {
    p_savings_status == "A".to_string()
}

fn savings_closed(p_savings_status: &str) -> bool {
    p_savings_status == "C".to_string()
}

fn savings_frozen(p_savings_status: &str) -> bool {
    p_savings_status == "F".to_string()
}

fn checking_active(p_checking_status: &str) -> bool {
    p_checking_status == "A".to_string()
}

fn checking_closed(p_checking_status: &str) -> bool {
    p_checking_status == "C".to_string()
}

fn checking_frozen(p_checking_status: &str) -> bool {
    p_checking_status == "F".to_string()
}

fn credit_active(p_credit_status: &str) -> bool {
    p_credit_status == "A".to_string()
}

fn credit_closed(p_credit_status: &str) -> bool {
    p_credit_status == "C".to_string()
}

fn credit_frozen(p_credit_status: &str) -> bool {
    p_credit_status == "F".to_string()
}

// Working Storage variables (static mut for COBOL global state model)
static mut ws_transfer_amt: f64 = 0.0;
#[allow(unused_variables)] static mut return_code: i64 = 0;
static mut savings_account: SavingsAccount = SavingsAccount { savings_acct_id: String::new(), savings_acct_name: String::new(), savings_balance: 0.0, savings_int_rate: 0.0, savings_status: String::new() };
static mut checking_account: CheckingAccount = CheckingAccount { checking_acct_id: String::new(), checking_acct_name: String::new(), checking_balance: 0.0, checking_int_rate: 0.0, checking_status: String::new() };
static mut credit_account: CreditAccount = CreditAccount { credit_acct_id: String::new(), credit_acct_name: String::new(), credit_balance: 0.0, credit_int_rate: 0.0, credit_status: String::new() };

fn main() {
    unsafe { savings_account.savings_acct_id = " ".repeat(12); }
    unsafe { savings_account.savings_acct_name = " ".repeat(30); }
    unsafe { savings_account.savings_status = " ".repeat(1); }
    unsafe { checking_account.checking_acct_id = " ".repeat(12); }
    unsafe { checking_account.checking_acct_name = " ".repeat(30); }
    unsafe { checking_account.checking_status = " ".repeat(1); }
    unsafe { credit_account.credit_acct_id = " ".repeat(12); }
    unsafe { credit_account.credit_acct_name = " ".repeat(30); }
    unsafe { credit_account.credit_status = " ".repeat(1); }
    unsafe { ws_transfer_amt = 0 as f64; }
    unsafe {

        savings_account.savings_acct_id = "SAV-001-2026".to_string().clone();
        savings_account.savings_acct_name = "Smith, John".to_string().clone();
        savings_account.savings_balance = 50000.00_f64;
        savings_account.savings_int_rate = 0.0325_f64;
        savings_account.savings_status = "A".to_string();
        checking_account.checking_acct_id = "CHK-001-2026".to_string().clone();
        checking_account.checking_acct_name = "Smith, John".to_string().clone();
        checking_account.checking_balance = 12500.00_f64;
        checking_account.checking_int_rate = 0.0010_f64;
        checking_account.checking_status = "A".to_string();
        credit_account.credit_acct_id = "CRD-001-2026".to_string().clone();
        credit_account.credit_acct_name = "Smith, John".to_string().clone();
        credit_account.credit_balance = -3200.00_f64;
        credit_account.credit_int_rate = 0.1999_f64;
        credit_account.credit_status = "A".to_string();
        ws_transfer_amt = 1000.00_f64;
        savings_account.savings_balance = savings_account.savings_balance - ((ws_transfer_amt as f64));
        checking_account.checking_balance = checking_account.checking_balance + (ws_transfer_amt as f64);
        println!("{}{:+011.2}", "After transfer of ".to_string(), ws_transfer_amt);
        println!("{}{:+011.2}", "Savings:  ".to_string(), savings_account.savings_balance);
        println!("{}{:+011.2}", "Checking: ".to_string(), checking_account.checking_balance);
        println!("{}{:+011.2}", "Credit:   ".to_string(), credit_account.credit_balance);
        process::exit(0);
    }
}

