//! Transpiled from COBOL program: PACKED-ARITH
//! Generated by Easy COBOL Migrator on 2026-03-23T05:38:00

#![allow(dead_code, non_upper_case_globals, static_mut_refs, unused_unsafe)]

use std::process;


// Working Storage variables (static mut for COBOL global state model)
static mut ws_price: f64 = 0.0;
static mut ws_qty: i64 = 0;
static mut ws_discount: f64 = 0.0;
static mut ws_tax_rate: f64 = 0.0;
static mut ws_subtotal: f64 = 0.0;
static mut ws_discount_amt: f64 = 0.0;
static mut ws_tax_amt: f64 = 0.0;
static mut ws_total: f64 = 0.0;
static mut ws_unit_price: f64 = 0.0;
#[allow(unused_variables)] static mut return_code: i64 = 0;

fn main() {
    unsafe { ws_price = 12345.67_f64; }
    unsafe { ws_qty = 150; }
    unsafe { ws_discount = 0.075_f64; }
    unsafe { ws_tax_rate = 0.1925_f64; }
    unsafe { ws_subtotal = 0 as f64; }
    unsafe { ws_discount_amt = 0 as f64; }
    unsafe { ws_tax_amt = 0 as f64; }
    unsafe { ws_total = 0 as f64; }
    unsafe { ws_unit_price = 0 as f64; }
    unsafe {

        ws_subtotal = (((ws_price as f64) * (ws_qty as f64)) * 100.0_f64).round() / 100.0_f64;
        ws_discount_amt = (((ws_subtotal as f64) * (ws_discount as f64)) * 100.0_f64).round() / 100.0_f64;
        ws_total = (ws_subtotal as f64) - ((ws_discount_amt as f64));
        ws_tax_amt = (((ws_total as f64) * (ws_tax_rate as f64)) * 100.0_f64).round() / 100.0_f64;
        ws_total = (ws_total as f64) + (ws_tax_amt as f64);
        ws_unit_price = (((ws_total as f64) / (ws_qty as f64)) * 10000.0_f64).round() / 10000.0_f64;
        println!("{}{:+011.2}", "Subtotal:     ".to_string(), ws_subtotal);
        println!("{}{:+011.2}", "Discount:     ".to_string(), ws_discount_amt);
        println!("{}{:+011.2}", "Tax:          ".to_string(), ws_tax_amt);
        println!("{}{:+011.2}", "Total:        ".to_string(), ws_total);
        println!("{}{:+011.4}", "Unit price:   ".to_string(), ws_unit_price);
        process::exit(0);
    }
}

