//! Transpiled from COBOL program: CALL-PATTERN
//! Generated by Easy COBOL Migrator on 2026-03-23T05:38:34

#![allow(dead_code, non_upper_case_globals, static_mut_refs, unused_unsafe)]

use std::process;


fn ws_is_valid(p_ws_valid_flag: &str) -> bool {
    p_ws_valid_flag == "Y".to_string()
}

fn ws_is_invalid(p_ws_valid_flag: &str) -> bool {
    p_ws_valid_flag == "N".to_string()
}

// Working Storage variables (static mut for COBOL global state model)
static mut ws_principal: f64 = 0.0;
static mut ws_rate: f64 = 0.0;
static mut ws_years: i64 = 0;
static mut ws_interest: f64 = 0.0;
static mut ws_first_name: String = String::new();
static mut ws_last_name: String = String::new();
static mut ws_full_name: String = String::new();
static mut ws_amount: f64 = 0.0;
static mut ws_min_amount: f64 = 0.0;
static mut ws_max_amount: f64 = 0.0;
static mut ws_valid_flag: String = String::new();
static mut ws_total_interest: f64 = 0.0;
#[allow(unused_variables)] static mut return_code: i64 = 0;

fn main_program() {
    unsafe {
        ws_principal = 50000.00_f64;
        ws_rate = 0.0450_f64;
        ws_years = 5;
        calc_interest();
        println!("{}{:+011.2}", "Interest (50K, 4.5%, 5yr): ".to_string(), ws_interest);
        ws_total_interest = (ws_total_interest as f64) + (ws_interest as f64);
        ws_principal = 100000.00_f64;
        ws_rate = 0.0325_f64;
        ws_years = 10;
        calc_interest();
        println!("{}{:+011.2}", "Interest (100K, 3.25%, 10yr): ".to_string(), ws_interest);
        ws_total_interest = (ws_total_interest as f64) + (ws_interest as f64);
        println!("{}{:+014.2}", "Total interest: ".to_string(), ws_total_interest);
        ws_first_name = "John".to_string().clone();
        ws_last_name = "Smith".to_string().clone();
        format_name();
        println!("{}{}", "Formatted: ".to_string(), ws_full_name);
        ws_amount = 5000.00_f64;
        ws_min_amount = 100.00_f64;
        ws_max_amount = 10000.00_f64;
        validate_amount();
        if ws_is_valid(&ws_valid_flag) {
            println!("{}", "Amount 5000.00 is valid".to_string());
        } else {
            println!("{}", "Amount 5000.00 is invalid".to_string());
        }
        ws_amount = 50000.00_f64;
        validate_amount();
        if ws_is_valid(&ws_valid_flag) {
            println!("{}", "Amount 50000.00 is valid".to_string());
        } else {
            println!("{}", "Amount 50000.00 is invalid".to_string());
        }
        process::exit(0);
    }
}


fn calc_interest() {
    unsafe {
        ws_interest = (((ws_principal as f64) * (ws_rate as f64)) * 100.0_f64).round() / 100.0_f64;
        (ws_years as f64) = ((ws_interest as f64) * (ws_years as f64)) as i64;
    }
}


fn format_name() {
    unsafe {
        let mut _result = String::new();
        _result.push_str(&format!("{}", ws_last_name).split(" ".to_string().as_str()).next().unwrap_or(""));
        _result.push_str(&format!("{}", ", ".to_string()));
        _result.push_str(&format!("{}", ws_first_name).split(" ".to_string().as_str()).next().unwrap_or(""));
        ws_full_name = _result;
    }
}


fn validate_amount() {
    unsafe {
        ws_valid_flag = "N".to_string();
        if ws_amount >= ws_min_amount && ws_amount <= ws_max_amount {
            ws_valid_flag = "Y".to_string();
        }
    }
}


fn main() {
    unsafe { ws_principal = 0 as f64; }
    unsafe { ws_rate = 0 as f64; }
    unsafe { ws_years = 0; }
    unsafe { ws_interest = 0 as f64; }
    unsafe { ws_first_name = " ".to_string(); }
    unsafe { ws_last_name = " ".to_string(); }
    unsafe { ws_full_name = " ".to_string(); }
    unsafe { ws_amount = 0 as f64; }
    unsafe { ws_min_amount = 0 as f64; }
    unsafe { ws_max_amount = 0 as f64; }
    unsafe { ws_valid_flag = "N".to_string(); }
    unsafe { ws_total_interest = 0 as f64; }
    unsafe {

        main_program();
    }
}

